services:
  - type: web
    name: takfinance
    branch: main
    plan: starter
    domains:
      - takfinance.onrender.com
    envVars:
      - fromGroup: takfinance-bot
    runtime: node
    startCommand: pnpm start
    buildCommand: pnpm install && tsc
